Nop.Plugin.Misc.PrintCalculator/Controllers/PrintCalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Plugin.Misc.PrintCalculator.Models;
using Nop.Services.Plugins;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;
using Nop.Services.Common;
using Nop.Core.Infrastructure;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Net.Http.Headers;
using PdfSharpCore.Pdf.IO;
using PdfSharpCore.Pdf;
using System.Drawing;
using Nop.Services.Catalog;
using Nop.Core.Domain.Catalog;
using Nop.Services.Logging;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;
using System.Text.Json;
using Nop.Services.Seo;
using System.Drawing.Imaging;
using Nop.Services.Media;
using Nop.Services.Security;
using Nop.Services.Configuration;
using Nop.Services.Messages;
using Nop.Core;

namespace Nop.Plugin.Misc.PrintCalculator.Controllers
{
    //[AutoValidateAntiforgeryToken]

    public class PrintCalculatorController : BasePluginController
    {
        private readonly ILogger _logger;
        private readonly IPictureService _pictureService;
        private readonly IProductService _productService;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        
        private readonly INotificationService _notificationService;
        private readonly ICategoryService _categoryService;

        private readonly IStoreContext _storeContext = EngineContext.Current.Resolve<IStoreContext>();


        private readonly string _fileUploadsDirectory = "printUploads";
        private readonly string _jobDescriptionDirectory = "printJobDescription";

        private PrintCalculatorSettings _printCalculatorSettings;


        public PrintCalculatorController(ILogger logger, 
            IProductService productService, 
            IPictureService pictureService, 
            IPermissionService permissionService, 
            ISettingService settingService, 
            INotificationService notificationService,
            ICategoryService categoryService)
        {
            _logger = logger;
            _productService = productService;
            _pictureService = pictureService;
            _permissionService = permissionService;
            _settingService = settingService;
            _notificationService = notificationService;
            _categoryService = categoryService;
        }


        [AuthorizeAdmin] //confirms access to the admin panel
        [Area(AreaNames.Admin)] //specifies the area containing a controller or action
        public async Task<IActionResult> Configure()
        {
            _printCalculatorSettings = await _settingService.LoadSettingAsync<PrintCalculatorSettings>((await _storeContext.GetCurrentStoreAsync()).Id);
            //prepare model
            var model = new ConfigurationModel()
            {
                PrintCategoryID = _printCalculatorSettings.PrintCategoryID
            };

            return View("~/Plugins/Misc.PrintCalculator/Views/Configure.cshtml", model);
        }

        [AuthorizeAdmin] //confirms access to the admin panel
        [Area(AreaNames.Admin)] //specifies the area containing a controller or action
        [HttpPost, ActionName("Configure")]
        public async Task<IActionResult> Configure(ConfigurationModel model)
        {
            _printCalculatorSettings = await _settingService.LoadSettingAsync<PrintCalculatorSettings>((await _storeContext.GetCurrentStoreAsync()).Id);

            //save settings
            _printCalculatorSettings.PrintCategoryID = model.PrintCategoryID;
            await _settingService.SaveSettingAsync(_printCalculatorSettings);

            _notificationService.SuccessNotification("PrintCalculator settings changed.");

            return await Configure();
        }

        public async Task<IActionResult> FileUpload()
        {
            return View("~/Plugins/Misc.PrintCalculator/Views/FileUpload.cshtml");
        }

        public async Task<IActionResult> ImageUpload()
        {
            return View("~/Plugins/Misc.PrintCalculator/Views/ImageUpload.cshtml");
        }

        private bool CheckExtensions(IFormFile file)
        {
            if (file == null)
                return false;

            if (file.FileName == null)
                return false;

            var extension = Path.GetExtension(file.FileName);
            var supportedExtensions = new List<string> { ".jpg", ".jpeg", ".png", ".tiff", ".tif", ".pdf", ".bmp", ".gif" };

            bool extensionCheck = false;
            supportedExtensions.ForEach(x =>
            {
                if (string.Equals(x, extension, StringComparison.OrdinalIgnoreCase))
                    extensionCheck = true;
            });

            if (!extensionCheck)
                return false;

            return true;
        }

        private async Task<string> GenerateNewFile(string extension, IFormFile file)
        {
            try
            {
                string filename = Guid.NewGuid() + extension;

                using (FileStream output = System.IO.File.Create(Path.Combine(_fileUploadsDirectory, filename)))
                {
                    await file.CopyToAsync(output);
                }

                return filename;

            }
            catch (Exception e)
            {
                await _logger.InsertLogAsync(Core.Domain.Logging.LogLevel.Error, "Print file upload error", e.Message);
                return null;
            }
        }

        private async Task<string> GenerateBase64Thumbnail(string imagePath)
        {
            Image img = Image.FromFile(imagePath);
            int thumbWidth = 300;
            int ratio = img.Height / img.Width;
            int thumbHeight = ratio * thumbWidth;
            Image thumb = img.GetThumbnailImage(thumbWidth, thumbHeight, null, IntPtr.Zero);
            using (MemoryStream m = new MemoryStream())
            {
                thumb.Save(m, ImageFormat.Png);
                byte[] imageBytes = m.ToArray();

                // Convert byte[] to Base64 String
                string base64String = Convert.ToBase64String(imageBytes);
                return "data:image/png;base64," + base64String;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile file)
        {
            if(CheckExtensions(file) == false)
            {
                return BadRequest();
            }
            var extension = Path.GetExtension(file.FileName);
            var model = new FileModel();

            Directory.CreateDirectory(_fileUploadsDirectory);
            Directory.CreateDirectory(_jobDescriptionDirectory);

            model.Extension = extension;
            model.Readable = true;

            string filename = await GenerateNewFile(extension, file);
            if (filename == null)
            {
                return StatusCode(500);
            }
            
            model.Name = filename;
            model.Extension = extension;
            model.Location = Path.Combine(_fileUploadsDirectory, filename);


            string existingPath = Path.Combine(_fileUploadsDirectory, model.Name);

            switch (extension)
            {
                case ".pdf":
                    var fs = System.IO.File.OpenRead(existingPath);
                    PdfDocument inputDocument = PdfReader.Open(fs, PdfDocumentOpenMode.Import);
                    if (inputDocument.SecuritySettings.PermitExtractContent == false)
                    {
                        return BadRequest();
                    }
                    model.PageCount = inputDocument.PageCount;
                    await fs.DisposeAsync();
                    break;
                default:
                    model.Thumbnail = await GenerateBase64Thumbnail(existingPath);
                    model.PageCount = 1;
                    break;
            }

            try
            {
                string descriptionFileName = model.Name + ".desc";

                using FileStream createStream = System.IO.File.Create(Path.Combine(_jobDescriptionDirectory, descriptionFileName));
                await JsonSerializer.SerializeAsync(createStream, model);
                await createStream.DisposeAsync();
            }
            catch (Exception e)
            {
                await _logger.InsertLogAsync(Core.Domain.Logging.LogLevel.Error, "Print job description save error", e.Message);
                return StatusCode(500);
            }

            return Ok("Customize?filename=" + model.Name);
        }

        [HttpPost]
        public async Task<IActionResult> UploadImg(IFormFile file)
        {
            if (CheckExtensions(file) == false)
            {
                return BadRequest();
            }

            var model = new ImageModel();
            var extension = Path.GetExtension(file.FileName);


            Directory.CreateDirectory(_fileUploadsDirectory);
            Directory.CreateDirectory(_jobDescriptionDirectory);

            model.Extension = extension;
            model.Readable = true;

            string filename = await GenerateNewFile(extension, file);
            if (filename == null)
            {
                return StatusCode(500);
            }

            model.Name = filename;

            string existingPath = Path.Combine(_fileUploadsDirectory, model.Name);
            model.Thumbnail = await GenerateBase64Thumbnail(existingPath);

            try
            {
                string descriptionFileName = model.Name + ".desc";

                using FileStream createStream = System.IO.File.Create(Path.Combine(_jobDescriptionDirectory, descriptionFileName));
                await JsonSerializer.SerializeAsync(createStream, model);
                await createStream.DisposeAsync();
            }

Nop.Plugin.Misc.PrintCalculator/Views/Configure.cshtml
@model Nop.Plugin.Misc.PrintCalculator.Models.ConfigurationModel

@{
    Layout = "_ConfigurePlugin";
}

<form asp-controller="PrintCalculator" asp-action="Configure" method="post">
    <div class="content">
        <div class="form-horizontal">
            <nop-cards>
                <nop-card asp-icon="fas fa-info" asp-title="Konfiguracija" asp-advanced="false">
                    <div class="form-group row">
                        <div class="col-md-3">
                            <nop-label asp-for="PrintCategoryID" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="PrintCategoryID" asp-required="true" />
                            <span asp-validation-for="PrintCategoryID"></span>
                        </div>
                    </div>
                </nop-card>
                <div class="form-group row">
                    <div class="col-md-9 offset-md-3">
                        <button type="submit" class="btn btn-info">
                            Submit
                        </button>
                    </div>
                </div>
            </nop-cards>
        </div>
    </div>
</form>

Nop.Plugin.Misc.PrintCalculator/Views/CustomizeImage.cshtml
@model Nop.Plugin.Misc.PrintCalculator.Models.CustomizeImageModel
@using Nop.Web.Framework.UI
@{
    Layout = "_ColumnsOne";
    var priceOptions = Model.Options;
}

@{ 
    var collection = @Html.Raw(Json.Serialize(Model.Options));
    var loadScript = "initPrice(" + collection + ")";

    string BP = "BasePrice";

    var priceCode = $@"<script>
                    $('#thumbnail').val($('#preview_img').attr('src'))
                    var priceSpan = $('#price')
                    var priceDict = {collection}
                    var inputPaperType = $('#PaperType')
                    var inputWitdhInCm = $('#WidthInCm')
                    var inputHeightInCm = $('#HeightInCm')
                    var height = {Model.HeightInCm}
                    var width = {Model.WidthInCm}
                    inputWitdhInCm.val(width.toFixed(2))
                    inputHeightInCm.val(height.toFixed(2))
                    var ratio = {Model.HeightInCm / Model.WidthInCm}
                    var basePrice = {Model.Options[BP]}
                    $('#submit-print').click(function() {{$('body').addClass('loading')}})

                    function updatePrice() {{
                        var price = basePrice * inputWitdhInCm.val() * inputHeightInCm.val()
                        var paperTypeKey = inputPaperType.find('option:selected').val();
                        price *= priceDict[paperTypeKey]
                        priceSpan.text(price.toFixed(2))
                    }}
                    $(document).ready(updatePrice)
                    inputHeightInCm.click(updatePrice)    
                    inputWitdhInCm.click(updatePrice)
                    inputPaperType.click(updatePrice)

                    inputPaperType.change(updatePrice)

                    inputWitdhInCm.change(function() {{ (inputHeightInCm.val((ratio * inputWitdhInCm.val()).toFixed(2)))}})
                    inputHeightInCm.change(function() {{ (inputWitdhInCm.val(((1/ratio) * inputHeightInCm.val()).toFixed(2)))}})
    </script>
    ";
    Html.AddInlineScriptParts(ResourceLocation.Footer, priceCode);


}
<head>
    <style>

    </style>
    <link rel="stylesheet" href="@Url.Content("~/Plugins/Misc.PrintCalculator/Views/Styles/Customize.css")">
    <link rel="stylesheet" href="@Url.Content("~/Plugins/Misc.PrintCalculator/Views/Styles/Spinner.css")">
</head>
<div class="overlay"></div>
<form asp-controller="Print" asp-action="CreateImage" method="post">
    <div id="print-preview">
        <div>
            <img id="preview_img" alt="" src="@Model.Thumbnail" />
        </div>
        <div id="print-details">
            <div class="spacer"></div>
            <div>
                <div class="option">
                    @T("Plugins.Misc.PrintCalculator.PrintOptions.ImageType"):
                    @Html.DropDownListFor(x => Model.PaperType, new SelectList(Model.PaperType, "Value", "Text"), htmlAttributes: new { id = "PaperType" })
                </div>
                <div class="spacer"></div>
                <div class="option">
                    @T("Plugins.Misc.PrintCalculator.PrintOptions.WidthInCm")
                    <input type="number" name="WidthInCm" id="WidthInCm" step=".01"/>
                </div>
                 <div class="spacer"></div>
                <div class="option">
                    @T("Plugins.Misc.PrintCalculator.PrintOptions.HeightInCm")
                    <input type="number" name="HeightInCm" id="HeightInCm" step=".01"/>
                </div>
                <div class="spacer"></div>
                <div class="option">
                    <strong>
                        @T("Plugins.Misc.PrintCalculator.PrintOptions.Price"):
                        <span id="price">0</span> KM
                    </strong>
                </div>
                <div class="option">
                    @T("Plugins.Misc.PrintCalculator.PrintOptions.NextStep")
                </div>
                <div class="spacer"></div>
            </div>
            <input type="hidden" name="name" value="@Model.Reference" />
            <input type="hidden" id="thumbnail" name="thumbnail" />
            <input type="submit" id="submit-print" value="@T("Plugins.Misc.PrintCalculator.PrintOptions.Submit")" />
        </div> 
    </div>
</form>

Nop.Plugin.Misc.PrintCalculator/Views/FileCustomize.cshtml
@model Nop.Plugin.Misc.PrintCalculator.Models.FileModel

<em>@Model.Name</em><br />
<em>@Model.Extension</em><br />
<em>@Model.Location</em><br />

Nop.Plugin.Misc.PrintCalculator/Views/FileUpload.cshtml
@{
    Layout = "_ColumnsOne";
}
<head>
    <script type="text/javascript">
        var fileobj;
        function upload_file(e) {
            e.preventDefault();
            fileobj = e.dataTransfer.files[0];
            ajax_file_upload(fileobj);
        }

        function file_explorer() {
            document.getElementById('selectfile').click();
            document.getElementById('selectfile').onchange = function () {
                fileobj = document.getElementById('selectfile').files[0];
                ajax_file_upload(fileobj);
            };
        }

        function ajax_file_upload(file_obj) {
            if (file_obj != undefined) {
                var size = parseFloat(file_obj.size / 1024).toFixed(2);
                if (size > 15000) {
                    alert("@T("Plugins.Misc.PrintCalculator.PrintOptions.MaxSizeAlert")");
                } else {
                    $('body').addClass('loading');
                    var form_data = new FormData();
                    form_data.append('file', file_obj);
                    $.ajax({
                        type: 'POST',
                        url: 'Upload/',
                        contentType: false,
                        encodingType: "multipart/form-data",
                        processData: false,
                        data: form_data,
                        success: function (response) {
                            if (response) {
                                window.location.href = response
                            }
                            $('#selectfile').val('');
                        }
                    });
                }
            }
        }
    </script>
    <link rel="stylesheet" href="@Url.Content("~/Plugins/Misc.PrintCalculator/Views/FileUpload.css")">
    <link rel="stylesheet" href="@Url.Content("~/Plugins/Misc.PrintCalculator/Views/Styles/Spinner.css")">
    <link rel="stylesheet" href="@Url.Content("~/Plugins/Misc.PrintCalculator/Views/Styles/FileUpload.css")">
</head>

<div class="overlay"></div>
<div id="drop_file_zone" ondrop="upload_file(event)" ondragover="return false">
    <div id="drag_upload_file">
        <p>@T("Plugins.Misc.PrintCalculator.PrintOptions.DragAndDrop")</p>
        <p>@T("Plugins.Misc.PrintCalculator.PrintOptions.Or")</p>
        <p><input type="button" class="file-submit-button" value="@T("Plugins.Misc.PrintCalculator.PrintOptions.SelectFile")" onclick="file_explorer();"></p>
        <input type="file" id="selectfile">
    </div>
</div>
<p>@T("Plugins.Misc.PrintCalculator.PrintOptions.SupportedFormatsText")@T("Plugins.Misc.PrintCalculator.PrintOptions.SupportedFormats")</p>
<p>@T("Plugins.Misc.PrintCalculator.PrintOptions.MaxSizeText")@T("Plugins.Misc.PrintCalculator.PrintOptions.MaxSize")</p>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

Nop.Plugin.Misc.PrintCalculator/Views/ImageUpload.cshtml
@{
    Layout = "_ColumnsOne";
}
<head>
    <script type="text/javascript">
        var fileobj;
        function upload_file(e) {
            e.preventDefault();
            fileobj = e.dataTransfer.files[0];
            ajax_file_upload(fileobj);
        }

        function file_explorer() {
            document.getElementById('selectfile').click();
            document.getElementById('selectfile').onchange = function () {
                fileobj = document.getElementById('selectfile').files[0];
                ajax_file_upload(fileobj);
            };
        }

        function ajax_file_upload(file_obj) {
            if (file_obj != undefined) {
                var size = parseFloat(file_obj.size / 1024).toFixed(2);
                if (size > 15000) {
                    alert("@T("Plugins.Misc.PrintCalculator.PrintOptions.MaxSizeAlert")");
                } else {
                    $('body').addClass('loading');
                    var form_data = new FormData();
                    form_data.append('file', file_obj);
                    $.ajax({
                        type: 'POST',
                        url: 'UploadImg/',
                        contentType: false,
                        encodingType: "multipart/form-data",
                        processData: false,
                        data: form_data,
                        success: function (response) {
                            if (response) {
                                window.location.href = response
                            }
                            $('#selectfile').val('');
                        }
                    });
                }
            }
        }
    </script>
</head>
<link rel="stylesheet" href="@Url.Content("~/Plugins/Misc.PrintCalculator/Views/FileUpload.css")">
<link rel="stylesheet" href="@Url.Content("~/Plugins/Misc.PrintCalculator/Views/Styles/Spinner.css")">
<link rel="stylesheet" href="@Url.Content("~/Plugins/Misc.PrintCalculator/Views/Styles/FileUpload.css")">
<div class="overlay"></div>
<div id="drop_file_zone" ondrop="upload_file(event)" ondragover="return false">
    <div id="drag_upload_file">
        <p>@T("Plugins.Misc.PrintCalculator.PrintOptions.DragAndDrop")</p>
        <p>@T("Plugins.Misc.PrintCalculator.PrintOptions.Or")</p>
        <p><input type="button" class="file-submit-button" value="@T("Plugins.Misc.PrintCalculator.PrintOptions.SelectFile")" onclick="file_explorer();"></p>
        <input type="file" id="selectfile">
    </div>
</div>
<p>@T("Plugins.Misc.PrintCalculator.PrintOptions.SupportedFormatsText")@T("Plugins.Misc.PrintCalculator.PrintOptions.SupportedFormats")</p>
<p>@T("Plugins.Misc.PrintCalculator.PrintOptions.MaxSizeText")@T("Plugins.Misc.PrintCalculator.PrintOptions.MaxSize")</p>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>